name: Ryan Shi
description: >
    Ryan Shi

master_repo: false
url: http://ryanzshi.github.io
markdown: kramdown
highlighter: rouge



rtl: false
owner:
  name:           Ryan
# Analytics and webmaster tools stuff goes here
google_analytics: G-MD93CPCDBY
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
